##
http://localhost:8080/api/alunos
###
curl -X POST http://localhost:8080/api/usuarios \
  -H "Content-Type: application/json" \
  -d '{"nome":"Coord Ana","email":"ana@coord.com","senha":"123","papel":"COORDENADOR"}'

  ###
  POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
curl -X POST http://localhost:8080/api/usuarios \
  -H "Content-Type: application/json" \
  -d '{"nome":"Coord Ana","email":"ana@coord.com","senha":"123","papel":"COORDENADOR"}'