## Listar todos os alunos
GET http://localhost:8080/api/alunos


### CRIAR UM USUARIO DE PERFIL COORDENADOR
curl -X POST http://localhost:8080/api/usuarios \
  -H "Content-Type: application/json" \
  -d '{
  "nome": "João Silva",
  "email": "joao@mail.com",
  "senha": "123456",
  "perfil": {
    "id": 1,
    "nome": "COORDENADOR"
  }
}'

### LISTAR TODOS OS USUARIOS
GET http://localhost:8080/api/usuarios
###
GET http://localhost:8080/api/plantoes